= Justin Ong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Buddy

---

== Overview

Student Buddy is a desktop application tailored for users who are comfortable with using a Command Line Interface (CLI), while retaining a Graphical User Interface (GUI) for ease of use. The use of a CLI for user input allows users to manage their tasks more efficiently than when using a conventional user interface.

== Summary of contributions

The following list is a summary of my contributions to the project Student Buddy.

* *Major enhancement*: added a *calendar panel* to the GUI for *easy viewing of tasks and their deadlines*.
** What it does: allows the user to view their tasks in a format that is familiar and easy to read. In addition, tasks are ordered and colour-coded by priority (high to low).
** Justification: This feature improves the product significantly because a user is able to quickly and easily see what tasks are due and when, facilitating better time management.
** Highlights: This enhancement piggybacks off of existing infrastructure, so future changes to underlying systems may cause the enhancement to break. It required an in-depth study of new concepts, as GUI modification was completely new to me before this project. I also wrote tests to ensure that the enhancement was working correctly.

* *Minor enhancement*: adjusted the GUI as features were added and modified.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Project management:
*** Deployed release v1.3.1.
** Enhancements to other features:
*** Assisted in adding a due date display to the task card list in the GUI (Pull request https://github.com/CS2113-AY1819S2-M11-2/main/pull/94[#94])
*** Assisted in formatting and presentation of notes function in the GUI (https://github.com/CS2113-AY1819S2-M11-2/main/pull/119[#119])
** Documentation:
*** Updated contents of the User and Developer Guides: (https://github.com/CS2113-AY1819S2-M11-2/main/pull/36[#36], https://github.com/CS2113-AY1819S2-M11-2/main/pull/84[#84], https://github.com/CS2113-AY1819S2-M11-2/main/pull/90[#90], https://github.com/CS2113-AY1819S2-M11-2/main/pull/1089[#108], https://github.com/CS2113-AY1819S2-M11-2/main/pull/109[#109], https://github.com/CS2113-AY1819S2-M11-2/main/pull/119[#119])
** Tools:
*** Integrated Coveralls to the team repo

== Contributions to the User Guide

|===
|_Given below are my contributions to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=calendar]

== Contributions to the Developer Guide

|===
|_Given below are my contributions to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=calendar]
