= Khairul - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Task Manager

---

== Overview

Student Buddy is a task manager desktop application. It is a GUI app but most of its user interactions happen in the Command Line Interface (CLI). It is targeted to students who have difficulty keeping track of their tasks and additional notes.

== Summary of contributions
This section shows a summary of my coding, documentation, and other helpful contributions to the team project.

* *Major enhancement*: added *the ability to `sort` tasks*
** What it does: It allows the user to sort the tasks in the task list based on name, module code, date due or priority level.
** Justification: This feature improves significantly because it allows the user to organise the task list in a manner of their choosing.
** Highlights: It required an in-depth analysis and understanding on how the different components of the task manager is involved with each other.

* *Minor enhancement*: created a `daysLeft` function to find number of days remaining till the task is due and gave colour codes depending on how much days are left.

* *Minor enhancement*: created `findname`, `findmodule`, `finddate` and `findpriority` commands to be able to search not only by task name but by other variables.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Set up the organization repository and its issue tracker
*** Managed releases `v1.2` and `v1.3` on GitHub
** Documentation:
*** Update images in the Developer Guide
*** Wrote use cases and user stories

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc
