= Nicholas Lee - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Student Buddy

---

== Overview

Student Buddy is an application that is used for university students to view, sort and manage their tasks effectively.
Students interact with it via the CLI or GUI that is created with JavaFX. It is written in Java, and has about 10kLoC.


== Summary of contributions

* *Major enhancement*: added *login feature*

** What it does:
*** Allows the user to create a personal account by signing up.
*** Upon signing up, the user is able to sign in and logout whenever they want to.
*** Subsequent logins will allow the user to access their personal Student Buddy.
*** With an normal account, only a logged in user will be able to add, edit or delete tasks in their Student Buddy.


** Justification:
*** This feature improves the product significantly because a user
can have their tasks secured without anyone messing with it.


** Highlights:
*** This enhancement affects existing commands and commands to be added in future.
It requires an in-depth analysis of design alternatives.
The implementation too was challenging as it required changes to existing commands.


** Credits: GSON Java library.
*** Gson is a Java library that can be used to convert Java Objects into their JSON representation.
*** It can also be used to convert a JSON string to an equivalent Java object.
*** In taskmanager, GSON Java library is used to convert the account's username and password,
which is in Java Object form, into JSON representation to be stored in a JSON file.
Vice versa, for retrieving the JSON representation in the JSON file and converting
into Java Objects to be read by other classes.


* *Minor enhancement*:
*** All passwords are hashed before storing
*** Added admin feature
**** An admin is able to delete user accounts
**** An admin is able to use any commands like a normal user
*** Changed files to binary file


* *Code contributed*:
[https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_


* *Other contributions*:

** Project management:
*** Managed merge and release of `v1.4` on GitHub
*** Added labels for organising and prioritising issues, pull request, merging.
This makes project management more efficient and effective.
*** PRs reviewed and merged (with non-trivial review comments):
https://github.com/CS2113-AY1819S2-M11-2/main/pull/32[#32],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/80[#80],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/82[#82],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/86[#86],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/88[#88],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/90[#90],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/105[#105],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/111[#111],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/119[#119],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/120[#120],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/121[#121],


** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 88% to 92%
(Pull requests
https://github.com/CS2113-AY1819S2-M11-2/main/pull/63[#63],
https://github.com/CS2113-AY1819S2-M11-2/main/pull/100[#100])

** Documentation:
*** Updated User Guide:
https://github.com/CS2113-AY1819S2-M11-2/main/pull/77[#77]
https://github.com/CS2113-AY1819S2-M11-2/main/pull/78[#78]
*** Updated Developer Guide:
https://github.com/CS2113-AY1819S2-M11-2/main/pull/87[#87]
https://github.com/CS2113-AY1819S2-M11-2/main/pull/103[#103]
https://github.com/CS2113-AY1819S2-M11-2/main/pull/107[#107]
*** Did About Us Documentation:
https://github.com/CS2113-AY1819S2-M11-2/main/blob/master/docs/AboutUs.adoc[AboutUs]

** Integrate major feature into entire application
*** The login feature I added was implemented in all other commands which worked together with my class mates work
(https://github.com/CS2113-AY1819S2-M11-2/main/pull/101[#101])


** Tools:
*** Integrated a third party library (GSON) to the project (https://github.com/CS2113-AY1819S2-M11-2/main/pull/83[#83])


== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=loginfunction]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=loginfunction]


== PROJECTS:

---
=== Vincent

https://github.com/nicholasleeeee/01-04-02[CG1112]

=== FPGA

https://github.com/Nicholas-Kayden/EE2026[EE2026] +



