= PROJECT: Student Buddy
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Kayden - Project Portfolio
This portfolio serves to document my contributions in a team-based software enginnering project CS2113T. My team comprises of 4 memebers and we were tasked to morph a basic command line interface addressbook within 8 weeks. After some discussion, we decided that we will work towards a Task Manager, Student Buddy.

---

== Overview

Our project's ultimate aim is to help students organise their tasks and notes more efficiently and effectively. This is done through the following features. Student Buddy allows users to add and delete their tasks and miscellaneous notes; view tasks added easily via a calendar panel display; as well as incorporate a signup and login feature to strengthen the security of this application.

My role was to design and implement the `notes` feature which allows user to `add` and `delete` miscellaneous notes as well as display them in a clear and concise manner. The following sections will highlight my enhancements in more detail, as well as illustrating the relevant sections that I have contributed to the user and developer guide.

== Summary of contributions
This section showcases the different aspects in which I have contributed to the project. These aspects include coding and the updating of user and developer guide.

* *Major enhancement*: added *the ability to `add notes` and `delete notes`*
** What it does: allows the user to add in new notes to help keep track and manage notes. Unwanted notes or notes that are already completed can be removed by deleting the note.
** Justification: This feature improves the product significantly because a user can now manage their miscellaneous activities other than school-related tasks which greatly enhances the useablility of Task Manager.
** Highlights: This enhancement required an in-depth analysis and understanding of the design of Task Manager to know what are its restrictions and how it can be improved.
** Credits: All the team members.

* *Minor enhancement*: Added colour codes to depict the importance of a note according to `priority` levels 1 to 3. The highest priority 1 being red-orange followed by yellow for 2 and white for 3.

* *Sample code contributed*: [https://github.com/Shengkok/main/blob/master/src/main/java/seedu/address/logic/commands/AddNotesCommand.java[Functional code]] [https://github.com[Test code]]

* *Other contributions*:

** Enhancements to existing features:
*** Updated the GUI of the application by adding a panel to display notes: https://github.com/CS2113-AY1819S2-M11-2/main/pull/56[#56]
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com/CS2113-AY1819S2-M11-2/main/pull/31[#31]
*** Added notes section for user guide which comprise of add notes and delete notes feature.
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my *ability to write documentation* targeting end-users._
|===

{Start of extract}

include::../UserGuide.adoc[tag=notes]

{End of extract}

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my *ability to write technical documentation* and the technical depth of my contributions to the project._
|===

{Start of extract}

include::../DeveloperGuide.adoc[tag=notes]

{End of extract}
